# Generated by Django 4.0.1 on 2022-01-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_recipe_favorite_recipes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopList',
            new_name='ShoppingCart',
        ),
    ]
