# Generated by Django 4.0.1 on 2022-01-22 15:08

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_tag_name_alter_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amount',
            name='count',
        ),
        migrations.AddField(
            model_name='amount',
            name='amount',
            field=models.IntegerField(default=1, validators=[recipes.validators.validate_amount]),
        ),
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='asd', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(validators=[recipes.validators.validate_time]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(related_name='recipe', to='recipes.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(related_name='recipe', to='recipes.Tag'),
        ),
    ]
