# Generated by Django 4.0.1 on 2022-02-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_favorite_recipes_alter_recipe_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='recipes',
            field=models.ManyToManyField(related_name='favorite', to='recipes.Recipe', verbose_name='рецепты'),
        ),
    ]
