# Generated by Django 4.0.1 on 2022-02-05 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_alter_recipe_options_recipe_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
