# Generated by Django 4.0.1 on 2022-02-07 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_remove_favorite_unique_user_recipes_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_recipe',
        ),
    ]
